name: internship_hb
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  titled_navigation_bar:
  flutter_launcher_icons:
  google_maps_flutter:
  flutter_polyline_points: ^0.1.0
  flutter_swiper:
  geocoder: ^0.2.1
  dio: ^3.0.9
  photo_view: ^0.9.2
  geolocator: ^5.3.0
  flutter_google_places: ^0.2.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/plan.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/image1.png
    - images/crane.png
    - images/truck.png
    - images/cement1.png
    - images/pillar.png
    - images/brick.png
    - images/sand.png
    - images/gravel.png
    - images/brick1.png
    - images/image2.png
    - images/grocery.png
    - images/shop.png
    - images/delivery.png
    - images/home.png
    - images/gift.png
    - images/hm1.png
    - images/hm2.png
    - images/wallet.png
    - images/expert.png
    - images/clock.png
    - images/apple.png
    - images/op6.png
    - images/mi.png
    - images/hm3.png
    - images/hm4.png
    - images/geyser.png
    - images/ac.jpg
    - images/fridge.jpg
    - images/bathroom.png
    - images/sofa.jpg
    - images/oneplus.png
    - images/op7p.png
    - images/op7t.png
    - images/pic.jpg
    - images/laptop.png
    - images/truck.png
    - images/plumb.png
    - images/paint.png
    - images/geyser.jpg
    - images/mobile.png
    - images/shop/ad.png
    - images/shop/ad2.png
    - images/shop/ad3.png
    - images/shop/appliances.png
    - images/shop/banner.png
    - images/shop/banner2.png
    - images/shop/cell.png
    - images/shop/chip.png
    - images/shop/laptop.png
    - images/shop/user.png
    - images/shop/product.png
    - images/shop/wishlist.png
    - images/shop/mobile.png
    - images/shop/tv.png
    - images/shop/print.png
    - images/shop/lap.png
    - images/shop/lap2.png
    - images/shop/lap3.png
    - images/shop/lap4.png
    - images/shop/lap5.png
    - images/shop/lap6.png
    - images/shop/man.png
    - images/shop/mouse.png
    - images/shop/mouse2.png
    - images/shop/printer.png
    - images/shop/lap7.png
    - images/shop/back.jpg
    - images/shop/back2.jpg
    - images/shop/back3.jpg
    - images/shop/icons/lapIcon.png
    - images/shop/icons/softIcon.png
    - images/shop/icons/inIcon.png
    - images/shop/icons/sdIcon.png
    - images/shop/icons/printIcon.png
    - images/shop/icons/storeIcon.png
    - images/sellLaptop/cpu.png
    - images/sellLaptop/ram.png
    - images/sellLaptop/disk.png
    - images/sellLaptop/untick.png
    - images/sellLaptop/ticked.png
    - images/sellLaptop/screen.png
    - images/sellLaptop/keyboard.png
    - images/sellLaptop/battery.png
    - images/sellLaptop/speaker.png
    - images/sellLaptop/wifi.png
    - images/sellLaptop/charger.png
    - images/sellLaptop/touchPad.png
    - images/sellLaptop/microsoft.png
    - images/sellLaptop/samsung.png
    - images/sellLaptop/asus.png
    - images/sellLaptop/cd.png
    - images/shop/sft.png
    - images/pickAndDrop/bottomSheet.png
    - images/pickAndDrop/paywallet.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
